FROM alpine:3

# LABEL command
LABEL author="Yusuf Nur Wahid"
LABEL company="PT. Ucup" website="https://www.github.com/ynwahid"

RUN mkdir hello
RUN echo "Hello, world!" > "hello/world.txt"

# CMD command
CMD cat "hello/world.txt"